dist: trusty
sudo: required
 
install: true
script:
  - sudo -H apt-get install software-properties-common
  - sudo -H add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo -H apt-get update
  - sudo -H apt-get install python3.6
  - sudo -H python --version
  - curl -sS https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  - sudo -H pip3 install -r requirements.txt
  - python3.6 -m pytest * ./pipeline/unit_tests/unit_tests_jasminFile.py
