language: python
python:
  - "3.6"
dist: trusty
sudo: required

jobs:
  include:
    - stage: BUILD_INSTALL_LOCAL_LIBRARY
      script: ./pipeline/stages/build_install_local_library.sh
    - stage: RUN_UNIT_TESTS
      script: ./pipeline/stages/run_unit_tests.sh
