dist: trusty
sudo: required
 
install: true
script:
  - sudo -H apt-get install software-properties-common
  - sudo -H add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo -H apt-get update
  - sudo -H apt-get install python3.6
  - curl -sS https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - sudo /usr/bin/python3.6 awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
  - ./run_pipeline_stages.sh
