dist: trusty
sudo: required
 
install: true
script:
  - pwd && cd && pwd && echo $PYTHONPATH
  - sudo apt-get -qq install -y python3-pip
  - python3 --version
  - sudo -H pip3 install --upgrade pip
  - echo "### PWD AFTER PIP3 INSTALL ###" && pwd
