dist: trusty
sudo: required
 
install: true
script:
  - sudo -H apt-get -qq install software-properties-common
  - sudo -H add-apt-repository --yes ppa:deadsnakes/ppa
  - sudo -H apt-get -qq update
  - sudo -H apt-get -qq install python3.6
  - sudo -H apt-get -qq install python3.6-dev
  - curl -sS https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - which python3.6 | (read PY_PATH; sudo -H $PY_PATH ./awscli-bundle/install)
  - sudo -H which aws
  - which aws
  - # sudo -H pip3 install -r requirements.txt --quiet
  - #./pipeline/integration_tests/install_prerequisites.sh
  - # ./run_pipeline_stages.sh
