dist: trusty
sudo: required
 
install: true
script:
  - curl -sS https://bootstrap.pypa.io/get-pip.py | sudo -H python3
  - sudo -H pip3 install --upgrade pip
  - python3 --version
  - ./run_pipeline_stages.sh
